const DAY=new Date().toISOString().slice(0,10);const KEY="mysystem-v4-"+DAY;
const defaults=[
{id:"wake",time:"08:00",name:"Réveil — sortir du lit",cat:"Corps",desc:"Commencer la journée sans négocier avec le réveil.",xp:10,stat:"discipline"},
{id:"water",time:"08:20",name:"Boire un verre d’eau",cat:"Corps",desc:"Un petit signal simple pour démarrer.",xp:5,stat:"health"},
{id:"ready",time:"08:35",name:"Douche + s’habiller",cat:"Corps",desc:"Passer du mode sommeil au mode journée.",xp:10,stat:"energy"},
{id:"breakfast",time:"09:00",name:"Petit-déjeuner",cat:"Nutrition",desc:"Un repas simple qui te donne une base d’énergie.",xp:10,stat:"health"},
{id:"study",time:"10:00",name:"Bloc EPFL",cat:"Esprit",desc:"Un bloc concentré. Pas besoin de sauver le semestre en une matinée.",xp:30,stat:"knowledge"},
{id:"lunch",time:"12:30",name:"Pause repas",cat:"Nutrition",desc:"Manger correctement et faire une vraie pause.",xp:10,stat:"health"},
{id:"outside",time:"14:30",name:"Sortir 10–20 min",cat:"Équilibre",desc:"Changer d’environnement et remettre du mouvement.",xp:10,stat:"mood"},
{id:"social",time:"17:30",name:"Un vrai contact humain",cat:"Social",desc:"Un message, un appel ou un moment partagé.",xp:20,stat:"social"},
{id:"move",time:"19:00",name:"Bouger / sport",cat:"Physique",desc:"Une activité adaptée à ton énergie du jour.",xp:25,stat:"fitness"},
{id:"life",time:"20:30",name:"Une chose juste pour toi",cat:"Vie",desc:"Quelque chose qui n’existe pas uniquement pour être productif.",xp:20,stat:"mood"},
{id:"tomorrow",time:"22:30",name:"Préparer demain",cat:"Discipline",desc:"Réduire le nombre de décisions du matin.",xp:15,stat:"discipline"},
{id:"calm",time:"23:00",name:"Passer en mode calme",cat:"Récupération",desc:"Créer une transition vers le sommeil.",xp:15,stat:"recovery"}
];
const statDefs=[
["health","Santé","Énergie de base, récupération et habitudes utiles.","💚"],
["fitness","Physique","Mouvement, capacité et régularité sportive.","⚡"],
["knowledge","Connaissances","Études, apprentissage et compétences.","🧠"],
["discipline","Discipline","Capacité à agir même quand l’envie varie.","🛡"],
["social","Social","Relations, présence et ouverture aux autres.","◈"],
["mood","Équilibre","Humeur, plaisir et variété dans la vie.","☼"],
["recovery","Récupération","Sommeil, pauses et capacité à ralentir.","☾"],
["energy","Énergie","Qualité avec laquelle tu peux vivre ta journée.","✦"]
];
const mealIdeas=[
["🥣","Matin","Yaourt + avoine + fruit + quelques noix","Simple, rassasiant et facile à préparer."],
["🍳","Matin","Œufs + pain complet + fruit","Une base salée si tu préfères manger ainsi."],
["🍚","Midi","Riz + poulet/tofu + légumes","Un repas complet que tu peux préparer en quantité."],
["🥙","Midi","Wrap + protéine + crudités + sauce au yaourt","Pratique quand tu n’as pas beaucoup de temps."],
["🍌","Collation","Fruit + yaourt ou poignée de noix","À adapter à ta faim et à ton activité."],
["🍝","Soir","Pâtes + sauce tomate + légumes + source de protéines","Confortable et facile à varier."]
];
let state=load();
function load(){const old=localStorage.getItem(KEY);if(old)return JSON.parse(old);return{xp:0,done:[],mode:"normal",energy:7,mood:7,stats:{health:28,fitness:24,knowledge:31,discipline:27,social:23,mood:34,recovery:29,energy:36},pantry:["œufs","riz","fruits","yaourt"],journal:"",custom:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function lvl(){return Math.floor(state.xp/100)+1}
function pct(){return Math.round(state.done.length/(defaults.length+state.custom.length)*100)}
function go(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.go===id));renderAll();scrollTo({top:0,behavior:"smooth"})}
function toast(t){const e=document.getElementById("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function renderAll(){document.getElementById("level").textContent=lvl();document.getElementById("charLevel").textContent=lvl();renderHome();renderQuests();renderStats();renderNutrition();renderReport()}
function tasks(){return defaults.concat(state.custom)}
function nextTask(){return tasks().find(t=>!state.done.includes(t.id))}
function renderHome(){document.getElementById("todayXp").textContent=state.xp;document.getElementById("todayPct").textContent=pct()+"%";document.getElementById("energy").textContent=state.energy;document.getElementById("mood").textContent=state.mood;const q=nextTask();const box=document.getElementById("currentQuest");if(q){box.innerHTML='<div class="quest-hero"><div class="quest-kicker"><span>'+q.cat.toUpperCase()+'</span><span>'+q.time+'</span></div><div class="quest-title">'+q.name+'</div><div class="quest-desc">'+q.desc+'</div><div class="quest-foot"><span class="xp">+'+q.xp+' XP</span><button class="primary" onclick="completeTask(\''+q.id+'\')">✓ C’est fait</button></div></div>';document.getElementById("explore").innerHTML=""}else{box.innerHTML='<div class="quest-hero"><div class="eyebrow">JOURNÉE COMPLÈTE</div><div class="quest-title">Tu as fait ce qui comptait.</div><div class="quest-desc">Maintenant, le système passe en mode exploration : choisis quelque chose qui enrichit ta journée sans obligation de performance.</div></div>';renderExplore()}}
function completeTask(id){const q=tasks().find(x=>x.id===id);if(!q||state.done.includes(id))return;state.done.push(id);state.xp+=q.xp;state.stats[q.stat]=Math.min(100,(state.stats[q.stat]||20)+statGain(q.stat));if(q.stat==="mood")state.mood=Math.min(10,state.mood+.2);if(q.stat==="energy")state.energy=Math.min(10,state.energy+.2);toast("Quête terminée · +"+q.xp+" XP");save()}
function statGain(s){return["health","recovery"].includes(s)?0.5:["knowledge","discipline"].includes(s)?0.7:0.4}
function renderExplore(){document.getElementById("explore").innerHTML='<div class="section-head"><div><span class="eyebrow">MODE EXPLORATION</span><h2>Tu veux développer quoi ?</h2></div></div><div class="choice-grid"><button class="choice" onclick="addIdea(\'knowledge\')"><b>🧠 Approfondir ton esprit</b><small>Lire, apprendre ou travailler une compétence pendant 20–30 min.</small></button><button class="choice" onclick="addIdea(\'social\')"><b>◈ Nourrir tes relations</b><small>Créer un vrai moment avec quelqu’un.</small></button><button class="choice" onclick="addIdea(\'mood\')"><b>☼ Faire quelque chose qui te plaît</b><small>Une activité sans objectif de performance.</small></button><button class="choice" onclick="addIdea(\'fitness\')"><b>⚡ Bouger doucement</b><small>Marche, mobilité ou activité légère selon ton énergie.</small></button></div>'}
function addIdea(stat){const map={knowledge:["Mini-session d’apprentissage","Choisis un sujet et apprends quelque chose pendant 20 minutes."],social:["Créer un vrai contact","Envoie un message ou propose un moment à quelqu’un."],mood:["Une activité pour toi","Fais quelque chose que tu aurais envie de faire même sans XP."],fitness:["Bouger 20 minutes","Une activité légère, adaptée à ton niveau d’énergie."]};const a=map[stat];state.custom.push({id:"custom-"+Date.now(),time:"Maintenant",name:a[0],cat:"Exploration",desc:a[1],xp:10,stat});toast("Quête ajoutée");save()}
function renderQuests(){const list=document.getElementById("questList");list.innerHTML=tasks().map(q=>'<div class="q-row '+(state.done.includes(q.id)?"done":"")+'"><button class="q-check" onclick="completeTask(\''+q.id+'\')">'+(state.done.includes(q.id)?"✓":"")+'</button><span class="q-time">'+q.time+'</span><span class="q-name">'+q.name+'</span><span class="q-xp">+'+q.xp+'</span></div>').join("")}
function addCustomQuest(){const n=prompt("Nom de la quête ?");if(!n)return;state.custom.push({id:"custom-"+Date.now(),time:"Flexible",name:n,cat:"Perso",desc:"Une action choisie par toi.",xp:10,stat:"discipline"});save();toast("Nouvelle quête créée")}
function toggleMode(){state.mode=state.mode==="normal"?"light":"normal";document.getElementById("modeToggle").classList.toggle("on",state.mode==="normal");toast(state.mode==="normal"?"Mode normal":"Mode léger");save()}
function renderStats(){const el=document.getElementById("stats");el.innerHTML=statDefs.map(s=>'<div class="stat"><div class="stat-top"><span>'+s[3]+' '+s[1]+'</span><span>'+Math.round(state.stats[s[0]])+'/100</span></div><div class="statbar"><i style="width:'+state.stats[s[0]]+'%"></i></div></div>').join("")}
function renderNutrition(){document.getElementById("mealGrid").innerHTML=mealIdeas.map((m,i)=>'<div class="meal"><span>'+m[0]+'</span><b>'+m[1]+'</b><div>'+m[2]+'</div><p>'+m[3]+'</p></div>').join("");document.getElementById("pantry").innerHTML=state.pantry.map(x=>'<span class="chip">'+x+'</span>').join("")}
function shuffleMeal(){const m=mealIdeas[Math.floor(Math.random()*mealIdeas.length)];document.getElementById("mealNowTitle").textContent=m[0]+" "+m[1];document.getElementById("mealNowText").textContent=m[2]+" — "+m[3];toast("Idée adaptée à ta journée")}
function editPantry(){const x=prompt("Tes aliments disponibles, séparés par des virgules :",state.pantry.join(", "));if(x===null)return;state.pantry=x.split(",").map(s=>s.trim()).filter(Boolean);save()}
function renderReport(){const score=Math.min(100,Math.round(pct()*.65+state.mood*3+state.energy*2));document.getElementById("score").textContent=score;document.getElementById("scoreText").textContent=score>75?"Bonne journée : tu as avancé sans tout miser sur la perfection.":score>45?"Journée correcte : on garde ce qui a fonctionné et on simplifie le reste.":"Journée difficile : le but de demain est de repartir petit, pas de rattraper tout aujourd’hui.";document.getElementById("reportList").innerHTML='<div class="report-item"><b>⚡ '+state.xp+' XP gagnés</b><p>'+state.done.length+' actions terminées.</p></div><div class="report-item"><b>☺ Humeur '+state.mood+'/10 · Énergie '+state.energy+'/10</b><p>Ces valeurs restent des indicateurs déclaratifs, pas des diagnostics.</p></div>';document.getElementById("recommendations").innerHTML='<div class="rec"><b>01 · Protéger le début de journée</b><p>Préparer la première action de demain ce soir pour réduire la friction.</p></div><div class="rec"><b>02 · Garder une activité qui te plaît</b><p>Une vie utile doit aussi contenir des choses choisies pour le plaisir et les relations.</p></div><div class="rec"><b>03 · Ajuster plutôt que culpabiliser</b><p>Si ton énergie est basse, réduire l’intensité est une adaptation, pas un échec.</p></div>'}
function bubble(t,c){const e=document.createElement("div");e.className="bubble "+c;e.textContent=t;document.getElementById("chat").appendChild(e);document.getElementById("chat").scrollTop=99999}
function quick(t){document.getElementById("msg").value=t;send()}
async function send(){const input=document.getElementById("msg"),m=input.value.trim();if(!m)return;bubble(m,"me");input.value="";const fallback="Je prends ce que tu me dis comme contexte. Pour l’instant je peux déjà utiliser ton état local ; la prochaine connexion serveur donnera au Coach une vraie intelligence capable d’analyser ton historique et de modifier ton planning.";bubble(fallback,"coach");try{const r=await fetch("/api/coach",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:m,state})});if(r.ok){const d=await r.json();const last=document.querySelector("#chat .coach:last-child");if(last&&d.reply)last.textContent=d.reply}}catch(e){}}
function voiceJournal(){const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){toast("La dictée vocale n’est pas disponible ici");go("journal");return}const rec=new Speech();rec.lang="fr-FR";rec.interimResults=true;rec.continuous=false;document.getElementById("recordTitle").textContent="J’écoute…";document.getElementById("recordText").textContent="Parle naturellement. Tu peux t’arrêter quand tu as fini.";rec.onresult=e=>{let t="";for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;document.getElementById("journalText").value=t};rec.onend=()=>{document.getElementById("recordTitle").textContent="C’est enregistré";document.getElementById("recordText").textContent="Tu peux analyser ta journée maintenant.";go("journal")};rec.onerror=()=>{toast("Impossible d’utiliser le micro");go("journal")};rec.start()}
function analyzeJournal(){const t=document.getElementById("journalText").value.trim();if(!t){toast("Raconte-moi d’abord ta journée");return}state.journal=t;const low=t.toLowerCase();if(low.includes("fatigu")||low.includes("mal dorm"))state.energy=Math.max(1,state.energy-.5);if(low.includes("content")||low.includes("heureux")||low.includes("bien"))state.mood=Math.min(10,state.mood+.4);state.xp+=5;save();document.getElementById("journalResult").innerHTML='<div class="panel" style="margin-top:12px"><span class="eyebrow">LECTURE DU SYSTÈME</span><h3 style="margin:9px 0 5px">Ce que je retiens</h3><p style="color:var(--muted);font-size:12px;line-height:1.5">Tu viens de donner du contexte qualitatif à ta journée. Dans la version IA, ce texte servira à détecter les tendances, ajuster demain et proposer des changements réellement personnalisés.</p><button class="secondary wide" onclick="go(\'report\')">Voir mon bilan →</button></div>';toast("Journal analysé · +5 XP")}
function closeModal(){document.getElementById("modal").classList.remove("show")}
document.getElementById("msg").addEventListener("keydown",e=>{if(e.key==="Enter")send()});
document.getElementById("modeToggle").classList.toggle("on",state.mode==="normal");
bubble("Je suis ton centre de contrôle. Pour l’instant je connais ton état local ; bientôt je pourrai réellement raisonner sur ton historique et agir sur ton système.","coach");
renderAll();
if("serviceWorker" in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("./sw.js").catch(()=>{});