const KEY="mysystem-state";
const DAYKEY=()=>{const d=new Date();return "mysystem-"+d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")};
const defaults=[
{id:"wake",time:"08:00",name:"Réveil",cat:"BASE",desc:"Sortir du lit et ouvrir la journée.",xp:8,stat:"recovery"},
{id:"water",time:"08:20",name:"Eau + lumière",cat:"SANTÉ",desc:"Boire un verre d’eau et prendre un peu de lumière naturelle.",xp:8,stat:"health"},
{id:"shower",time:"08:35",name:"Douche",cat:"BASE",desc:"Te préparer sans chercher la perfection.",xp:8,stat:"discipline"},
{id:"breakfast",time:"09:00",name:"Petit-déjeuner",cat:"NUTRITION",desc:"Un vrai repas simple avant d’attaquer.",xp:10,stat:"health"},
{id:"epfl",time:"10:00",name:"Bloc EPFL",cat:"CONNAISSANCE",desc:"Un bloc de travail concentré. Une seule matière, un objectif clair.",xp:25,stat:"knowledge"},
{id:"lunch",time:"12:30",name:"Pause repas",cat:"RÉCUPÉRATION",desc:"Manger et faire une vraie coupure.",xp:10,stat:"health"},
{id:"outside",time:"14:30",name:"Sortir 10–20 min",cat:"ÉNERGIE",desc:"Changer d’environnement et bouger tranquillement.",xp:12,stat:"energy"},
{id:"social",time:"17:30",name:"Un vrai contact humain",cat:"SOCIAL",desc:"Envoyer un message, appeler quelqu’un ou passer un moment avec une personne.",xp:15,stat:"social"},
{id:"move",time:"19:00",name:"Bouger / sport",cat:"FORME",desc:"Une activité adaptée à ton énergie du jour.",xp:20,stat:"fitness"},
{id:"joy",time:"20:30",name:"Une chose juste pour toi",cat:"HUMEUR",desc:"Faire quelque chose qui te plaît sans le transformer en performance.",xp:12,stat:"mood"},
{id:"tomorrow",time:"22:30",name:"Préparer demain",cat:"ORGANISATION",desc:"Choisir une priorité et rendre demain plus facile.",xp:12,stat:"discipline"},
{id:"calm",time:"23:00",name:"Mode calme",cat:"RÉCUPÉRATION",desc:"Ralentir progressivement et protéger ta nuit.",xp:15,stat:"recovery"}
];
const freshState=()=>({xp:0,done:[],mode:"normal",energy:7,mood:7,stats:{health:28,fitness:24,knowledge:31,discipline:27,social:23,mood:34,recovery:29,energy:36},pantry:["œufs","riz","fruits","yaourt"],journal:"",custom:[],overrides:{},sleep:{wake:"08:00",fatigue:7,usual:"23:00"},history:[],coachLog:[]});
let state=loadState(), questFilter="all", updateWorker=null, reloadOnController=false;

function loadState(){try{const raw=JSON.parse(localStorage.getItem(KEY)||"null");return raw?merge(freshState(),raw):freshState()}catch(e){return freshState()}}
function merge(base,raw){return {...base,...raw,stats:{...base.stats,...(raw.stats||{})},sleep:{...base.sleep,...(raw.sleep||{})},custom:Array.isArray(raw.custom)?raw.custom:[],overrides:raw.overrides||{},done:Array.isArray(raw.done)?raw.done:[],history:Array.isArray(raw.history)?raw.history:[],coachLog:Array.isArray(raw.coachLog)?raw.coachLog:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(DAYKEY(),JSON.stringify({done:state.done,xp:state.xp,energy:state.energy,mood:state.mood,at:Date.now()}))}
function localDate(){return new Intl.DateTimeFormat("fr-CH",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}
function currentMinutes(){const d=new Date();return d.getHours()*60+d.getMinutes()}
function parseTime(t){if(!/^\d{2}:\d{2}$/.test(t||""))return null;const [h,m]=t.split(":").map(Number);return h*60+m}
function fmtTime(m){m=((m%1440)+1440)%1440;return String(Math.floor(m/60)).padStart(2,"0")+":"+String(m%60).padStart(2,"0")}
function tasks(){return defaults.concat(state.custom||[]).map(t=>{const o=state.overrides[t.id]||{};return {...t,time:o.time||t.time,name:o.name||t.name,desc:o.desc||t.desc,xp:Number.isFinite(o.xp)?o.xp:t.xp}})}
function taskStatus(t){if(state.done.includes(t.id))return"done";const m=parseTime(t.time);if(m===null)return"neutral";const d=m-currentMinutes();if(d<0)return"late";if(d<=45)return"now";return"next"}
function smartNextTask(){const all=tasks().filter(t=>!state.done.includes(t.id));if(!all.length)return null;const now=currentMinutes();const future=all.filter(t=>parseTime(t.time)!==null&&parseTime(t.time)>=now);if(future.length)return future.sort((a,b)=>parseTime(a.time)-parseTime(b.time))[0];return all.sort((a,b)=>(parseTime(a.time)||9999)-(parseTime(b.time)||9999))[0]}
function lvl(){return Math.max(1,Math.floor(state.xp/100)+1)}
function levelPct(){return state.xp%100}
function pct(){const all=tasks();return all.length?Math.round(state.done.length/all.length*100):0}
function toast(msg){const el=document.getElementById("toast");el.textContent=msg;el.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove("show"),2300)}
function go(id){document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===id));document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.go===id));window.scrollTo({top:0,behavior:"smooth"});renderAll()}
function bubble(text,who){const c=document.getElementById("chat");if(!c)return;const d=document.createElement("div");d.className="bubble "+who;d.textContent=text;c.appendChild(d);c.scrollTop=c.scrollHeight}
function quick(text){document.getElementById("msg").value=text;send()}
function completeTask(id){if(state.done.includes(id))return;const q=tasks().find(x=>x.id===id);if(!q)return;state.done.push(id);state.xp+=q.xp;state.stats[q.stat]=Math.min(100,(state.stats[q.stat]||0)+Math.max(1,Math.round(q.xp/8)));state.history.push({date:new Date().toISOString(),type:"complete",task:id,xp:q.xp});save();toast("Quête terminée · +"+q.xp+" XP");renderAll()}
function toggleMode(){state.mode=state.mode==="normal"?"light":"normal";save();toast(state.mode==="light"?"Mode léger activé":"Mode normal activé");renderAll()}
function setQuestFilter(f){questFilter=f;document.querySelectorAll(".filter").forEach(b=>b.classList.toggle("active",b.dataset.filter===f));renderQuests()}
function editTask(id){const q=tasks().find(x=>x.id===id);if(!q)return;const time=prompt("Nouvelle heure (HH:MM)",q.time);if(time===null)return;if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)){toast("Heure invalide");return}state.overrides[id]={...(state.overrides[id]||{}),time};save();toast("Horaire actualisé");renderAll()}
function addCustomQuest(){const name=prompt("Nom de la quête");if(!name?.trim())return;const time=prompt("Heure (HH:MM)",fmtTime(currentMinutes()+30));if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)){toast("Heure invalide");return}state.custom.push({id:"custom-"+Date.now(),time,name:name.trim(),cat:"PERSONNEL",desc:"Une action choisie pour aujourd’hui.",xp:10,stat:"discipline"});save();toast("Nouvelle quête créée");renderAll()}
function adjustEnergy(){const v=prompt("Énergie actuelle sur 10",String(state.energy));if(v===null)return;const n=Math.max(1,Math.min(10,Number(v)));if(!Number.isFinite(n))return;state.energy=n;save();renderAll()}
function adjustMood(){const v=prompt("Humeur actuelle sur 10",String(state.mood));if(v===null)return;const n=Math.max(1,Math.min(10,Number(v)));if(!Number.isFinite(n))return;state.mood=n;save();renderAll()}

function scheduleState(){const q=smartNextTask();if(!q)return{label:"SOCLE TERMINÉ",tone:"good",detail:"Plus de mission obligatoire. Le système te laisse choisir."};const m=parseTime(q.time);if(m===null)return{label:"FLEXIBLE",tone:"neutral",detail:"La prochaine action est flexible."};const d=m-currentMinutes();if(d<0)return{label:"EN RETARD",tone:"late",detail:"Pas de rattrapage automatique : on repart de maintenant."};if(d<=45)return{label:"MAINTENANT",tone:"now",detail:"La prochaine action arrive maintenant."};return{label:"DANS LES TEMPS",tone:"good",detail:"Tu as encore du temps avant la prochaine étape."}}
function renderClock(){const time=document.getElementById("clockTime"),date=document.getElementById("clockDate"),status=document.getElementById("clockStatus"),line=document.getElementById("clockLine"),tl=document.getElementById("timeline");if(!time)return;const now=currentMinutes();time.textContent=fmtTime(now);date.textContent=localDate();const ss=scheduleState();status.textContent=ss.label;status.className="status-chip "+ss.tone;document.getElementById("clockLineText").textContent=ss.detail;const start=420,end=1440,ratio=Math.max(0,Math.min(1,(now-start)/(end-start)));line.style.left=(ratio*100)+"%";tl.innerHTML=tasks().map(t=>{const m=parseTime(t.time);if(m===null)return"";const p=Math.max(0,Math.min(100,(m-start)/(end-start)*100));return '<button class="timeline-item '+taskStatus(t)+'" style="left:'+p+'%" onclick="focusTask(\''+t.id+'\')"><span>'+t.time+'</span><i></i><b>'+esc(t.name)+'</b></button>'}).join("")}
function focusTask(id){const q=tasks().find(x=>x.id===id);if(q)toast(q.time+" · "+q.name+" · +"+q.xp+" XP")}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function renderHome(){const q=smartNextTask(),ss=scheduleState();document.getElementById("streak").textContent="🔥 "+getStreak()+" jour"+(getStreak()>1?"s":"");document.getElementById("xpProgress").textContent=state.xp+" / "+(lvl()*100)+" XP";const badge=document.getElementById("scheduleBadge");badge.textContent=ss.label;badge.className="status-chip "+ss.tone;document.getElementById("scheduleBadge").title=ss.detail;document.getElementById("heroText").textContent=ss.tone==="late"?"Le planning a pris du retard. Pas grave : on repart de maintenant, sans dette.":"Une seule action importante maintenant. Le reste peut attendre.";document.getElementById("currentQuest").innerHTML=q?'<div class="quest-hero"><div class="quest-kicker"><span>'+esc(q.cat)+'</span><span>'+q.time+'</span></div><div class="quest-title">'+esc(q.name)+'</div><div class="quest-desc">'+esc(q.desc)+'</div><div class="quest-foot"><span class="xp">+'+q.xp+' XP</span><button class="primary" onclick="completeTask(\''+q.id+'\')">✓ C’est fait</button></div></div>':'<div class="quest-hero"><div class="eyebrow">SOCLE TERMINÉ</div><div class="quest-title">Tu es libre.</div><div class="quest-desc">Aucune mission obligatoire restante. Profite de l’espace ou crée une quête personnelle.</div></div>';document.getElementById("dayContext").innerHTML='<div class="day-context '+(ss.tone==="late"?"late":"")+'"><b>'+esc(ss.label)+'.</b> '+esc(ss.detail)+'</div>';const target=sleepCalc();document.getElementById("homeSleepStat").textContent=fmtTime(target.bed);document.getElementById("energy").textContent=state.energy;document.getElementById("mood").textContent=state.mood;document.getElementById("todayPct").textContent=pct()+"%";document.getElementById("todayXp").textContent=state.xp+" XP";document.getElementById("homeLevel").textContent=lvl();document.getElementById("homeXpBar").style.width=levelPct()+"%";document.getElementById("questProgressText").textContent=state.done.length+" / "+tasks().length+" missions";document.getElementById("homeNextText").textContent=q?q.time+" · "+q.name:"Socle terminé";document.getElementById("homeSleep").innerHTML='<div class="mini-sleep"><span class="eyebrow">CE SOIR</span><b>'+fmtTime(target.bed)+'</b><small>viser '+target.target+' h · lever '+state.sleep.wake+'</small><button class="ghost" onclick="go(\'sleep\')">Sommeil →</button></div>'}
function renderQuests(){const all=tasks(),next=smartNextTask();document.getElementById("questDone").textContent=state.done.length;document.getElementById("questLeft").textContent=all.length-state.done.length;document.getElementById("questXp").textContent=state.xp;const mode=document.getElementById("modeToggle");mode.textContent=state.mode==="normal"?"NORMAL":"LÉGER";mode.classList.toggle("light",state.mode==="light");let list=all;if(questFilter==="open")list=all.filter(q=>!state.done.includes(q.id));if(questFilter==="done")list=all.filter(q=>state.done.includes(q.id));document.getElementById("questList").innerHTML=list.length?list.map(q=>'<div class="q-row '+(state.done.includes(q.id)?"done ":"")+(next&&next.id===q.id?"next":"")+'"><button class="q-check" onclick="completeTask(\''+q.id+'\')">'+(state.done.includes(q.id)?"✓":"")+'</button><span class="q-time">'+q.time+'</span><span class="q-name">'+esc(q.name)+'</span><span class="q-xp">+'+q.xp+'</span><button class="q-edit" onclick="editTask(\''+q.id+'\')">↗</button></div>').join(""):'<div class="empty">Rien ici pour le moment.</div>'}
function renderStats(){const labels={health:"Santé",fitness:"Forme",knowledge:"Connaissance",discipline:"Discipline",social:"Social",mood:"Humeur",recovery:"Récupération",energy:"Énergie"};document.getElementById("stats").innerHTML=Object.entries(state.stats).map(([k,v])=>'<div class="stat"><div class="stat-top"><span>'+labels[k]+'</span><span>'+Math.round(v)+'</span></div><div class="statbar"><i style="width:'+Math.min(100,v)+'%"></i></div></div>').join("");document.getElementById("levelProgressText").textContent=levelPct()+"%";document.getElementById("levelProgressBar").style.width=levelPct()+"%";document.getElementById("statInsight").textContent=state.mode==="light"?"Le mode léger protège ta régularité quand ton énergie baisse. C’est une adaptation, pas un échec.":"Le système privilégie la régularité : les petites actions répétées comptent plus qu’une journée parfaite."}
const meals=[["🥣","Bol simple","Yaourt, avoine ou céréales, fruit et quelques noix."],["🍳","Œufs + tartine","Œufs, pain complet, fruit ou légumes selon l’envie."],["🍚","Bol riz","Riz, légumes, œufs/tofu/poulet et une sauce simple."],["🥙","Wrap complet","Galette, protéine, crudités et sauce au yaourt."],["🍝","Pâtes équilibrées","Pâtes, légumes, sauce tomate et une source de protéines."],["🥔","Assiette maison","Pommes de terre ou céréales, légumes et protéine."]];
function renderNutrition(){const h=new Date().getHours();const title=h<11?"Petit-déjeuner":h<15?"Déjeuner":h<19?"Goûter / pause":"Dîner";document.getElementById("mealNowTitle").textContent=title;document.getElementById("mealGrid").innerHTML=meals.slice(0,4).map(m=>'<div class="meal"><span>'+m[0]+'</span><b>'+m[1]+'</b><p>'+m[2]+'</p></div>').join("");document.getElementById("pantry").innerHTML=state.pantry.map(x=>'<span class="chip">'+esc(x)+'</span>').join("")||'<span class="chip">frigo vide</span>'}
function shuffleMeal(){const m=meals[Math.floor(Math.random()*meals.length)];document.getElementById("mealNowTitle").textContent=m[1];document.getElementById("mealNowText").textContent=m[2];toast("Idée changée")}
function editPantry(){const v=prompt("Sépare les aliments par des virgules",state.pantry.join(", "));if(v===null)return;state.pantry=v.split(",").map(x=>x.trim()).filter(Boolean);save();renderNutrition();toast("Frigo actualisé")}
function sleepCalc(){const wake=parseTime(state.sleep.wake)||480;const target=state.sleep.fatigue>=8?9:state.sleep.fatigue>=6?8.5:8;return{target,bed:wake-target*60}}
function renderSleep(){const p=state.sleep,c=sleepCalc(),wind=c.bed-45;document.getElementById("bedtime").textContent=fmtTime(c.bed);document.getElementById("sleepTarget").textContent=c.target+" h";document.getElementById("sleepFatigue").textContent=p.fatigue+"/10";document.getElementById("sleepWake").textContent=p.wake;document.getElementById("sleepWind").textContent=fmtTime(wind);document.getElementById("sleepStatus").textContent=p.fatigue>=8?"RÉCUPÉRATION PRIORITAIRE":p.fatigue>=6?"FATIGUE À PROTÉGER":"RYTHME STABLE";document.getElementById("sleepReason").textContent=p.fatigue>=8?"Ce soir, protège surtout une vraie période de repos.":p.fatigue>=6?"Ta fatigue est élevée : mieux vaut protéger une nuit suffisante que repousser le coucher.":"Garde surtout une heure de lever assez régulière.";document.getElementById("sleepPlan").innerHTML='<div class="sleep-step"><b>'+fmtTime(wind)+'</b><span>Mode calme</span><small>Lumière plus douce, activités tranquilles, préparer demain.</small></div><div class="sleep-step"><b>'+fmtTime(c.bed-15)+'</b><span>Fin des écrans stimulants</span><small>Si possible, passer à quelque chose de calme et peu stimulant.</small></div><div class="sleep-step"><b>'+fmtTime(c.bed)+'</b><span>Au lit</span><small>Objectif : laisser suffisamment de temps au sommeil, sans chercher la perfection.</small></div>';}
function openSleepSettings(){const content='<h3>Réglage du rythme</h3><label>Heure de lever cible</label><input id="modalWake" type="time" value="'+state.sleep.wake+'"><label>Fatigue actuelle (1–10)</label><input id="modalFatigue" type="number" min="1" max="10" value="'+state.sleep.fatigue+'"><div class="modal-actions"><button class="secondary" onclick="closeModal()">Annuler</button><button class="primary" onclick="saveSleepSettings()">Enregistrer</button></div>';document.getElementById("modalContent").innerHTML=content;document.getElementById("modal").classList.add("show")}
function saveSleepSettings(){const wake=document.getElementById("modalWake").value,f=Number(document.getElementById("modalFatigue").value);if(!/^\d\d:\d\d$/.test(wake)||!Number.isFinite(f))return;state.sleep.wake=wake;state.sleep.fatigue=Math.max(1,Math.min(10,f));save();closeModal();toast("Rythme actualisé");renderAll()}
function closeModal(){document.getElementById("modal").classList.remove("show")}

function score(){const base=pct(),energy=state.energy*10,mood=state.mood*10;return Math.min(100,Math.round(base*.72+energy*.12+mood*.16))}
function renderReport(){const s=score();document.getElementById("score").textContent=s;document.getElementById("scoreBar").style.width=s+"%";document.getElementById("scoreMood").textContent=state.mode==="light"?"MODE LÉGER":s>=70?"BON RYTHME":s>=40?"EN CONSTRUCTION":"DÉMARRAGE";document.getElementById("scoreText").textContent=s>=80?"Très bonne cohérence entre tes actions et ton énergie.":s>=50?"Tu avances. Le système peut surtout t’aider à garder le cap.":"Pas besoin de rattraper quoi que ce soit. Choisis une petite action utile.";const done=tasks().filter(q=>state.done.includes(q.id));document.getElementById("reportList").innerHTML=(done.length?done.slice(-5).reverse().map(q=>'<div class="report-item"><b>✓ '+esc(q.name)+'</b><span>+'+q.xp+' XP · '+q.cat+'</span></div>').join(""):'<div class="empty">Aucune quête terminée aujourd’hui. Une petite victoire suffit pour commencer.</div>');const q=smartNextTask();document.getElementById("recommendations").innerHTML=q?"Prochaine priorité : <b>"+esc(q.name)+"</b> à "+q.time+". Si ton énergie change, modifie-la ou demande au Coach de recalculer la suite.":"Le socle est terminé. Tu peux créer une quête personnelle ou simplement profiter de ton temps."}
function getStreak(){let n=state.done.length?1:0;for(let i=1;i<30;i++){const d=new Date();d.setDate(d.getDate()-i);const k="mysystem-"+d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");try{const s=JSON.parse(localStorage.getItem(k)||"null");if(s?.done?.length)n++;else break}catch(e){break}}return n}
function analyzeJournal(){const t=document.getElementById("journalText").value.trim();if(!t){toast("Écris ou raconte d’abord ta journée");return}state.journal=t;const low=t.toLowerCase();if(/fatigu|épuis|crevé|mal dorm/.test(low))state.energy=Math.max(1,+(state.energy-.5).toFixed(1));if(/content|heureux|bien passé|fier/.test(low))state.mood=Math.min(10,+(state.mood+.4).toFixed(1));state.xp+=5;state.coachLog.push({date:new Date().toISOString(),message:t});save();document.getElementById("journalResult").innerHTML='<div class="panel" style="margin-top:10px"><span class="eyebrow">CONTEXTE ENREGISTRÉ</span><p style="color:var(--muted);font-size:10px;line-height:1.5">Le système gardera ce retour comme contexte local. Le Coach IA pourra l’utiliser pour mieux adapter les prochaines décisions.</p></div>';toast("Journal enregistré · +5 XP");renderAll()}
function voiceJournal(){const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){toast("La dictée vocale n’est pas disponible ici");go("journal");return}const rec=new Speech();rec.lang="fr-FR";rec.interimResults=true;rec.continuous=false;document.getElementById("recordTitle").textContent="J’écoute…";document.getElementById("recordText").textContent="Parle naturellement. Je transcris ce que tu dis.";rec.onresult=e=>{let t="";for(let i=0;i<e.results.length;i++)t+=e.results[i][0].transcript;document.getElementById("journalText").value=t};rec.onend=()=>{document.getElementById("recordTitle").textContent="C’est enregistré";document.getElementById("recordText").textContent="Tu peux analyser ta journée maintenant.";go("journal")};rec.onerror=()=>toast("Impossible d’utiliser le micro");rec.start()}

function coachContextText(){const q=smartNextTask();return "Heure locale: "+fmtTime(currentMinutes())+" · énergie: "+state.energy+"/10 · humeur: "+state.mood+"/10 · mode: "+state.mode+" · progression: "+pct()+"% · prochaine quête: "+(q?q.time+" "+q.name:"aucune")+" · fatigue sommeil: "+state.sleep.fatigue+"/10"}
function localCoach(m){const low=m.toLowerCase();const tm=low.match(/(?:à|vers|pour)\s*(\d{1,2})[:h](\d{2})/);if((low.includes("déplace")||low.includes("décale")||low.includes("repousse")||low.includes("avance"))&&tm){const q=tasks().find(t=>low.includes(t.name.toLowerCase()));if(q){const time=tm[1].padStart(2,"0")+":"+tm[2];state.overrides[q.id]={...(state.overrides[q.id]||{}),time};save();renderAll();return"Je l’ai déplacée : « "+q.name+" » passe à "+time+"."}}if(low.includes("maintenant")||low.includes("quoi faire")){const q=smartNextTask();return q?"Fais seulement « "+q.name+" ». "+q.desc:"Ton socle est terminé. Tu es libre."}if(low.includes("organis"))return"Je regarde l’heure, ton énergie et les quêtes restantes. La prochaine priorité est « "+(smartNextTask()?.name||"une activité choisie")+" ».";if(low.includes("fatigu")||low.includes("dormi"))return"On baisse l’intensité. Le but est de protéger les essentiels et ta récupération, pas de tout rattraper.";return"Je garde ça comme contexte. Je peux déjà agir localement sur les quêtes ; avec l’IA connectée, je peux analyser plus finement ta situation."}
function applyCoachActions(actions){if(!Array.isArray(actions))return[];const changed=[];actions.forEach(a=>{if(a.type==="move_task"&&a.task_id&&/^([01]\d|2[0-3]):[0-5]\d$/.test(a.time||"")){state.overrides[a.task_id]={...(state.overrides[a.task_id]||{}),time:a.time};changed.push("horaire → "+a.time)}else if(a.type==="change_task"&&a.task_id){state.overrides[a.task_id]={...(state.overrides[a.task_id]||{}),...(a.name?{name:a.name}:{}),...(a.desc?{desc:a.desc}:{}),...(Number.isFinite(a.xp)?{xp:Math.max(1,Math.min(100,a.xp))}:{})};changed.push("quête modifiée")}else if(a.type==="add_task"&&a.name){state.custom.push({id:"ai-"+Date.now()+"-"+Math.random().toString(16).slice(2),time:/^([01]\d|2[0-3]):[0-5]\d$/.test(a.time||"")?a.time:fmtTime(currentMinutes()+30),name:a.name,cat:a.cat||"COACH",desc:a.desc||"Action proposée par le Coach.",xp:Number(a.xp)||10,stat:a.stat||"discipline"});changed.push("nouvelle quête")}else if(a.type==="remove_task"&&a.task_id){state.custom=state.custom.filter(t=>t.id!==a.task_id);delete state.overrides[a.task_id];changed.push("quête supprimée")}else if(a.type==="set_mode"&&(a.mode==="normal"||a.mode==="light")){state.mode=a.mode;changed.push("mode "+a.mode)}});if(changed.length)save();return changed}
async function send(){const input=document.getElementById("msg"),m=input.value.trim();if(!m)return;bubble(m,"me");input.value="";const placeholder=document.createElement("div");placeholder.className="bubble coach";placeholder.textContent="Je regarde ton système…";document.getElementById("chat").appendChild(placeholder);document.getElementById("chat").scrollTop=99999;document.getElementById("coachState").textContent="Analyse du contexte…";try{const r=await fetch("./api/coach",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:m,state,context:coachContextText(),tasks:tasks()})});if(!r.ok)throw new Error("offline");const d=await r.json();placeholder.textContent=d.reply||"J’ai analysé ta situation.";const changed=applyCoachActions(d.actions||[]);if(changed.length)bubble("⚙ Système ajusté · "+changed.join(" · "),"coach");state.coachLog.push({date:new Date().toISOString(),message:m,reply:d.reply||""});save();document.getElementById("coachState").textContent="GPT-6 Luna · système pilotable";renderAll()}catch(e){placeholder.textContent=localCoach(m);document.getElementById("coachState").textContent="Mode local · IA indisponible"}}
function resetToday(){if(!confirm("Réinitialiser les quêtes et XP de cette journée ?"))return;state.done=[];state.xp=0;save();toast("Journée réinitialisée");renderAll()}

function renderAll(){document.getElementById("level").textContent=lvl();document.getElementById("charLevel").textContent=lvl();document.getElementById("todayLabel").textContent=localDate().toUpperCase();document.getElementById("coachContext").textContent=coachContextText();renderHome();renderClock();renderQuests();renderStats();renderNutrition();renderSleep();renderReport()}

function setupUpdates(){if(!("serviceWorker"in navigator)||location.protocol==="file:")return;navigator.serviceWorker.register("./sw.js").then(reg=>{if(reg.waiting){updateWorker=reg.waiting;showUpdate()};reg.addEventListener("updatefound",()=>{const w=reg.installing;if(!w)return;w.addEventListener("statechange",()=>{if(w.state==="installed"&&navigator.serviceWorker.controller){updateWorker=w;showUpdate()}})});setInterval(()=>reg.update().catch(()=>{}),60000)}).catch(()=>{});navigator.serviceWorker.addEventListener("controllerchange",()=>{if(reloadOnController)location.reload()})}
function showUpdate(){document.getElementById("updateBanner").classList.add("show")}
function applyUpdate(){if(!updateWorker){location.reload();return}reloadOnController=true;updateWorker.postMessage({type:"SKIP_WAITING"});document.getElementById("updateBanner").classList.remove("show")}
document.getElementById("msg").addEventListener("keydown",e=>{if(e.key==="Enter")send()});
bubble("Je suis le centre de contrôle de MY SYSTEM. Dis-moi où tu en es vraiment : je peux t’aider à choisir la prochaine action et, quand l’IA est connectée, agir directement sur ton planning.","coach");
renderAll();setupUpdates();setInterval(()=>{renderClock();renderHome()},30000);